'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import type { ChatSkill } from '@/lib/api/chat'
import type { DailyCreationRule, DailyCreationRuleInput } from '@/lib/api/daily-plan'

type Directory = { id: number; name: string; asset_type: 'article' | 'media' }
type Account = { id: string; name: string }
const defaults: DailyCreationRuleInput = { name: '', asset_type: 'article', directory: '', directories: [], output_type: 'x_short_post', target_count: 3, execution_mode: 'recurring', scheduled_date: null, scheduled_time: '09:00', timezone: 'Asia/Shanghai', lookback_days: 14, delivery_mode: 'drafts', account_id: null, instructions: '', skill_mode: 'auto', skill_name: null, enabled: true }

export function CreationRuleDialog({ open, directories, accounts, skills, initial, onClose, onSubmit }: { open: boolean; directories: Directory[]; accounts: Account[]; skills: ChatSkill[]; initial?: DailyCreationRule | null; onClose: () => void; onSubmit: (input: DailyCreationRuleInput) => void | Promise<void> }) {
  const [value, setValue] = useState<DailyCreationRuleInput>(() => initial ? { name: initial.name, asset_type: initial.asset_type, directory: initial.directory, directories: initial.directories?.length ? initial.directories : initial.directory ? [initial.directory] : [], output_type: initial.output_type, target_count: initial.target_count, execution_mode: initial.execution_mode, scheduled_date: initial.scheduled_date, scheduled_time: initial.scheduled_time, timezone: initial.timezone, lookback_days: initial.lookback_days, delivery_mode: initial.delivery_mode, account_id: initial.account_id, instructions: initial.instructions, skill_mode: initial.skill_mode ?? 'auto', skill_name: initial.skill_name ?? null, enabled: initial.enabled } : defaults)
  const [error, setError] = useState('')
  if (!open) return null
  const set = <K extends keyof DailyCreationRuleInput>(key: K, next: DailyCreationRuleInput[K]) => setValue(previous => ({ ...previous, [key]: next }))
  return <div role="dialog" aria-modal="true" aria-label={initial ? '编辑创作规则' : '新建创作规则'} className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4">
    <form noValidate className="max-h-[calc(100vh-2rem)] w-full max-w-xl space-y-4 overflow-y-auto rounded-2xl border bg-background p-5 shadow-xl" onSubmit={event => { event.preventDefault(); if (value.directories.length === 0) { setError('请选择至少一个素材目录'); return } if (!value.name.trim()) { setError('请输入规则名称'); return } if (value.skill_mode === 'manual' && !value.skill_name) { setError('请选择 Skill'); return } if (value.execution_mode === 'once' && !value.scheduled_date) { setError('请选择执行日期'); return } if (value.delivery_mode === 'plan_items' && !value.account_id) { setError('请选择发布账号'); return } setError(''); void onSubmit({ ...value, directory: value.directories[0], skill_name: value.skill_mode === 'manual' ? value.skill_name : null }) }}>
      <div><h2 className="text-base font-semibold">{initial ? '编辑创作规则' : '新建创作规则'}</h2><p className="text-xs text-muted-foreground">AI 读取候选素材和全局历史，自主判断语义重复。</p></div>
      {error && <p role="alert" className="text-sm text-red-600">{error}</p>}
      <div className="grid gap-3 sm:grid-cols-2">
        <label className="space-y-1 text-sm">规则名称<input aria-label="规则名称" required value={value.name} onChange={e => set('name', e.target.value)} className="w-full rounded-lg border px-3 py-2" /></label>
        <label className="space-y-1 text-sm">素材类型<select aria-label="素材类型" value={value.asset_type} onChange={e => setValue(previous => ({ ...previous, asset_type: e.target.value as 'article' | 'media', directory: '', directories: [] }))} className="w-full rounded-lg border px-3 py-2"><option value="article">文章</option><option value="media">媒体</option></select></label>
        <fieldset aria-label="素材目录" className="space-y-2 sm:col-span-2"><div className="flex items-center justify-between text-sm"><legend>素材目录</legend><span className="text-xs text-muted-foreground">已选择 {value.directories.length} 个目录</span></div><div className="grid max-h-40 gap-2 overflow-y-auto rounded-lg border p-3 sm:grid-cols-2">{directories.filter(item => item.asset_type === value.asset_type).map(item => <label key={item.id} className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-muted"><input type="checkbox" checked={value.directories.includes(item.name)} onChange={event => { const selected = new Set(value.directories); if (event.target.checked) selected.add(item.name); else selected.delete(item.name); const ordered = directories.filter(directory => directory.asset_type === value.asset_type && selected.has(directory.name)).map(directory => directory.name); setValue(previous => ({ ...previous, directories: ordered, directory: ordered[0] ?? '' })) }} />{item.name}</label>)}{directories.every(item => item.asset_type !== value.asset_type) && <p className="text-xs text-muted-foreground">暂无可选目录</p>}</div></fieldset>
        <fieldset aria-label="Skill 模式" className="space-y-2 sm:col-span-2"><legend className="text-sm">创作 Skill</legend><div className="flex flex-wrap gap-4 rounded-lg border p-3 text-sm"><label className="flex items-center gap-2"><input type="radio" name="skill-mode" checked={value.skill_mode === 'auto'} onChange={() => setValue(previous => ({ ...previous, skill_mode: 'auto', skill_name: null }))} />自动匹配</label><label className="flex items-center gap-2"><input type="radio" name="skill-mode" checked={value.skill_mode === 'manual'} onChange={() => set('skill_mode', 'manual')} />手动指定</label></div></fieldset>
        {value.skill_mode === 'manual' && <label className="space-y-1 text-sm sm:col-span-2">指定 Skill<select aria-label="指定 Skill" value={value.skill_name ?? ''} onChange={event => set('skill_name', event.target.value || null)} className="w-full rounded-lg border px-3 py-2"><option value="">请选择</option>{value.skill_name && !skills.some(skill => skill.name === value.skill_name) && <option value={value.skill_name}>{value.skill_name}（不可用）</option>}{skills.map(skill => <option key={skill.name} value={skill.name}>{skill.name} · {skill.description}</option>)}</select></label>}
        <label className="space-y-1 text-sm">目标数量<input aria-label="目标数量" type="number" min={1} max={50} required value={value.target_count} onChange={e => set('target_count', Number(e.target.value))} className="w-full rounded-lg border px-3 py-2" /></label>
        <label className="space-y-1 text-sm">去重天数<input aria-label="去重天数" type="number" min={1} max={90} required value={value.lookback_days} onChange={e => set('lookback_days', Number(e.target.value))} className="w-full rounded-lg border px-3 py-2" /></label>
        <label className="space-y-1 text-sm">执行方式<select aria-label="执行方式" value={value.execution_mode} onChange={e => set('execution_mode', e.target.value as 'once' | 'recurring')} className="w-full rounded-lg border px-3 py-2"><option value="recurring">每天执行</option><option value="once">仅执行一次</option></select></label>
        {value.execution_mode === 'once' && <label className="space-y-1 text-sm">执行日期<input aria-label="执行日期" type="date" required value={value.scheduled_date ?? ''} onChange={e => set('scheduled_date', e.target.value || null)} className="w-full rounded-lg border px-3 py-2" /></label>}
        <label className="space-y-1 text-sm">执行时间<input aria-label="执行时间" type="time" required value={value.scheduled_time} onChange={e => set('scheduled_time', e.target.value)} className="w-full rounded-lg border px-3 py-2" /></label>
        <label className="space-y-1 text-sm">产出位置<select aria-label="产出位置" value={value.delivery_mode} onChange={e => set('delivery_mode', e.target.value as 'drafts' | 'plan_items')} className="w-full rounded-lg border px-3 py-2"><option value="drafts">保存为草稿</option><option value="plan_items">加入今日计划</option></select></label>
        {value.delivery_mode === 'plan_items' && <label className="space-y-1 text-sm">发布账号<select aria-label="发布账号" required value={value.account_id ?? ''} onChange={e => set('account_id', e.target.value || null)} className="w-full rounded-lg border px-3 py-2"><option value="">请选择</option>{accounts.filter(item => item.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
      </div>
      <label className="block space-y-1 text-sm">附加要求<textarea aria-label="附加要求" value={value.instructions} onChange={e => set('instructions', e.target.value)} className="min-h-20 w-full rounded-lg border px-3 py-2" /></label>
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>取消</Button><Button type="submit">保存规则</Button></div>
    </form>
  </div>
}
