services:
  api:
    volumes:
      - ./backend:/app

  web:
    command: ["./node_modules/.bin/next", "dev", "--hostname", "0.0.0.0"]
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    volumes:
      - ./web:/app
      - /app/node_modules
