import type { AppSettings } from './settings'

export function makeSettings(overrides: Partial<AppSettings> = {}): AppSettings {
  const settings = {
    llm_provider: 'openai',
    llm_model: 'gpt-4o-mini',
    llm_base_url: '',
    llm_effective_base_url: 'https://api.openai.com/v1',
    llm_api_key_set: false,
    llm_api_key_preview: '',
    image_model: 'gpt-image-1',
    image_base_url: '',
    image_api_key_set: false,
    image_api_key_preview: '',
    heygen_api_key_set: false,
    heygen_api_key_preview: '',
    transcription_provider: 'openai-compatible',
    transcription_model: 'whisper-1',
    transcription_base_url: 'https://api.openai.com/v1',
    transcription_api_key_set: false,
    transcription_api_key_preview: '',
    transcription_max_duration_seconds: 7200,
    transcription_max_audio_bytes: 26214400,
    rsshub_base: 'http://127.0.0.1:1200',
    github_token_set: false,
    github_token_preview: '',
    github_interval_minutes: 1,
    github_trending_interval_hours: 6,
    camofox_url: 'http://localhost:9377',
    camofox_api_key_set: false,
    camofox_user_id: 'wemedia_x',
    camofox_novnc_url: 'http://localhost:6080/vnc.html',
    x_collect_enabled: false,
    x_cookies_set: false,
    x_collect_interval_minutes: 15,
    x_notify_enabled: true,
    telegram_bot_token_set: false,
    telegram_bot_token_preview: '',
    telegram_chat_id: '',
    telegram_test_status: '',
    telegram_last_tested_at: '',
    telegram_last_test_error: '',
    x_response_account_id: '',
    x_follower_threshold: 10000,
    x_post_window_hours: 24,
    x_post_lookback_hours: 12,
    x_timeline_scrolls: 3,
    twitterapi_io_key_set: false,
    twitterapi_io_collect_enabled: false,
    x_search_queries: '',
    tl1_collect_enabled: false,
    tl1_collect_interval_seconds: 60,
    tl1_trending_hours: 24,
    x_post_classify_enabled: false,
    x_post_classify_prompt: '',
    arxiv_categories: 'cs.AI,cs.CL,cs.CV,cs.LG',
    arxiv_collect_interval_hours: 6,
    ref_collect_interval_minutes: 15,
    ref_classify_interval_minutes: 60,
    clean_batch_size: 20,
    wechat_tunnel_enabled: false,
    wechat_tunnel_ssh_host: '',
    wechat_tunnel_ssh_port: 22,
    wechat_tunnel_ssh_user: '',
    wechat_tunnel_ssh_key_path: '',
    wechat_tunnel_local_host: '127.0.0.1',
    wechat_tunnel_local_port: 18443,
    wechat_tunnel_remote_host: 'api.weixin.qq.com',
    wechat_tunnel_remote_port: 443,
    wechat_tunnel_extra_args: '',
    blog_api_base: 'https://mkflow.dev',
    blog_api_token_set: false,
    blog_api_token_preview: '',
    web_search_providers: [],
    web_fetch_providers: [],
    providers: [],
    ...overrides,
  } satisfies AppSettings

  return settings
}
